import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Footer } from '../components/footer'
import { Hero } from '../components/hero'
import { Navbar } from '../components/navbar'
import { Testimonials } from '../components/testimonials/testimonials'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Navbar />

      <main className="">
        <hr />
        <Hero />
        <hr />
        <Testimonials />
        <hr />

      </main>

      <Footer />
    </div>
  )
}

export default Home
